### ISSUE TITLE
Refactor: change name of CRUDTaskDefinition instance, task_definition, to crud_task_definition

### ISSUE THREAD

**Issue by lennertjansen** [orhanrauf/neena#27]
The current naming of this instance in `backend/app/crud/crud_task_definition.py` and the resulting imports im files like `backend/app/core/flow_generator.py` and `backend/app/core/task_definition_retriever.py` is ambiguous and confusing to work with when dealing with actual instances of the `TaskDefinition` class.

Proposing to change it to `crud_task_definition` to avoid ambiguity.

**Comment by orhanrauf** [comment]
Sure, just make sure when we refactor we do it across all entities. I would say no priority until we do the refactor batch

**Comment by orhanrauf** [comment]
Moving this to the project board
